language: python
python:
  - "2.7"
before_script:
  - psql -c 'create database bot;' -U postgres
  - lsb_release -a
  - sudo apt-get install -y mapnik
install: "pip install -r requirements.txt"
script:  PYTHONPATH="." python test/test.py
services:
  - postgresql