language: python
sudo: required
dist: trusty
python:
  - "2.7"
before_script:
  - psql -c 'create database bot;' -U postgres
  - sudo apt-get install -y python-software-properties
  - sudo add-apt-repository -y ppa:mapnik/nightly-2.3
  - sudo apt-get update
  - sudo apt-get install -y python-mapnik
install: "pip install -r requirements.txt"
script:  PYTHONPATH="." python test/test.py
services:
  - postgresql